version: '3.4'

services:
  personsapi:
    build:
        context: .
        dockerfile: ./Dockerfile-PersonsApi
    ports:
      - 5021:5021
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:5021;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=m2a6r3c0
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  lawsuitapi:
    build:
        context: .
        dockerfile: ./Dockerfile-LawSuitsApi
    ports:
      - 5011:5011
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:5011;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=m2a6r3c0
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
