FROM mcr.microsoft.com/dotnet/sdk:3.1 AS base
WORKDIR /app
EXPOSE 5021

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Mc2Tech.PersonsApi/Mc2Tech.PersonsApi.csproj", "Mc2Tech.PersonsApi/"]
RUN dotnet restore "Mc2Tech.PersonsApi/Mc2Tech.PersonsApi.csproj"
COPY . .
WORKDIR "/src/Mc2Tech.PersonsApi"
RUN dotnet build "Mc2Tech.PersonsApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Mc2Tech.PersonsApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Mc2Tech.PersonsApi.dll"]