FROM mcr.microsoft.com/dotnet/sdk:3.1 AS base
WORKDIR /app
EXPOSE 5011

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Mc2Tech.LawSuitsApi/Mc2Tech.LawSuitsApi.csproj", "Mc2Tech.LawSuitsApi/"]
RUN dotnet restore "Mc2Tech.LawSuitsApi/Mc2Tech.LawSuitsApi.csproj"
COPY . .
WORKDIR "/src/Mc2Tech.LawSuitsApi"
RUN dotnet build "Mc2Tech.LawSuitsApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Mc2Tech.LawSuitsApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Mc2Tech.LawSuitsApi.dll"]